wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1702401955.279658
    t:
      1:
      - 49
      - 55
      - 86
      - 92
      - 95
      - 96
      - 105
      2:
      - 49
      - 55
      - 86
      - 92
      - 95
      - 96
      - 105
      3:
      - 23
      4: 3.11.4
      5: 0.16.1
      8:
      - 2
      - 5
      9:
        2: langchain
      13: linux-x86_64
